Repository inssagram/BE, pull requests merged in 2023-11, with the labels that each got.

#31 feat: comment 기능에 멘션 할 수 있는 기능 추가
  src/main/java/com/be/inssagram/domain/comment/dto/request/CommentRequest.java
  src/main/java/com/be/inssagram/domain/comment/dto/response/CommentInfoResponse.java
  src/main/java/com/be/inssagram/domain/comment/dto/response/ReplyInfoResponse.java
  src/main/java/com/be/inssagram/domain/comment/entity/Comment.java
  src/main/java/com/be/inssagram/domain/comment/service/CommentService.java
Labels: enhancement

#32 Feat/token insert
  src/main/java/com/be/inssagram/config/Jwt/filter/JwtAuthenticateFilter.java
  src/main/java/com/be/inssagram/domain/comment/controller/CommentController.java
  src/main/java/com/be/inssagram/domain/comment/dto/request/CommentRequest.java
  src/main/java/com/be/inssagram/domain/comment/service/CommentService.java
  src/main/java/com/be/inssagram/domain/like/controller/LikeController.java
  src/main/java/com/be/inssagram/domain/like/service/LikeService.java
  src/main/java/com/be/inssagram/domain/post/controller/PostController.java
  src/main/java/com/be/inssagram/domain/post/dto/request/CreatePostRequest.java
  src/main/java/com/be/inssagram/domain/post/service/PostService.java
  src/test/java/com/be/inssagram/domain/post/controller/PostControllerTest.java
  src/test/java/com/be/inssagram/domain/post/service/PostServiceTest.java
Labels: enhancement

#33 fix: 일부 서비스 조회 기능 사용 시 발생하는 영속성 오류 fix
  src/main/java/com/be/inssagram/domain/comment/service/CommentService.java
  src/main/java/com/be/inssagram/domain/hashTag/service/HashTagService.java
  src/main/java/com/be/inssagram/domain/like/service/LikeService.java
  src/main/java/com/be/inssagram/domain/post/service/PostService.java
  src/main/java/com/be/inssagram/domain/tag/service/TagService.java
Labels: bug

#35 fix: comment API 요청 방식 수정
  src/main/java/com/be/inssagram/domain/comment/controller/CommentController.java
  src/main/java/com/be/inssagram/domain/comment/dto/request/CommentRequest.java
  src/main/java/com/be/inssagram/domain/comment/service/CommentService.java
Labels: enhancement

#36 2023-11-07: 대보수
  src/main/java/com/be/inssagram/domain/bookmark/controller/BookmarkController.java
  src/main/java/com/be/inssagram/domain/bookmark/dto/request/BookmarkRequest.java
  src/main/java/com/be/inssagram/domain/bookmark/dto/response/BookmarkResponse.java
  src/main/java/com/be/inssagram/domain/bookmark/entity/Bookmark.java
  src/main/java/com/be/inssagram/domain/bookmark/repository/BookmarkRepository.java
  src/main/java/com/be/inssagram/domain/bookmark/service/BookmarkService.java
  src/main/java/com/be/inssagram/domain/comment/controller/CommentController.java
  src/main/java/com/be/inssagram/domain/comment/dto/request/CommentRequest.java
  src/main/java/com/be/inssagram/domain/comment/service/CommentService.java
  src/main/java/com/be/inssagram/domain/elastic/controller/ElasticSearchController.java
  src/main/java/com/be/inssagram/domain/elastic/documents/index/HashtagIndex.java
  src/main/java/com/be/inssagram/domain/elastic/documents/repository/HashtagSearchRepository.java
  src/main/java/com/be/inssagram/domain/elastic/dto/request/SearchRequest.java
  src/main/java/com/be/inssagram/domain/elastic/dto/response/SearchResult.java
  src/main/java/com/be/inssagram/domain/elastic/service/ElasticSearchService.java
  src/main/java/com/be/inssagram/domain/follow/controller/FollowController.java
  src/main/java/com/be/inssagram/domain/follow/dto/response/FollowerList.java
  src/main/java/com/be/inssagram/domain/follow/dto/response/FollowingList.java
  src/main/java/com/be/inssagram/domain/follow/entity/Follow.java
  src/main/java/com/be/inssagram/domain/follow/repository/FollowRepository.java
  src/main/java/com/be/inssagram/domain/follow/service/FollowService.java
  src/main/java/com/be/inssagram/domain/hashTag/service/HashTagService.java
  src/main/java/com/be/inssagram/domain/like/service/LikeService.java
  src/main/java/com/be/inssagram/domain/member/service/MemberService.java
  src/main/java/com/be/inssagram/domain/notification/controller/NotificationController.java
  src/main/java/com/be/inssagram/domain/notification/dto/NotificationRequest.java
  src/main/java/com/be/inssagram/domain/notification/dto/request/MessageInfo.java
  src/main/java/com/be/inssagram/domain/notification/dto/request/NotificationRequest.java
  src/main/java/com/be/inssagram/domain/notification/dto/response/NotificationResponse.java
  src/main/java/com/be/inssagram/domain/notification/entity/Notification.java
  src/main/java/com/be/inssagram/domain/notification/repository/NotificationRepository.java
  src/main/java/com/be/inssagram/domain/notification/service/NotificationService.java
  src/main/java/com/be/inssagram/domain/stroy/controller/StoryController.java
  src/main/java/com/be/inssagram/domain/stroy/dto/request/CreateStoryRequest.java
  src/main/java/com/be/inssagram/domain/stroy/dto/response/StoryInfoResponse.java
  src/main/java/com/be/inssagram/domain/stroy/entity/Story.java
  src/main/java/com/be/inssagram/domain/stroy/repository/StoryRepository.java
  src/main/java/com/be/inssagram/domain/stroy/service/StoryService.java
Labels: enhancement

#37 feat: story 기능에 스케쥴러, 생성 후 지난 시간 추가
  src/main/java/com/be/inssagram/InssagramApplication.java
  src/main/java/com/be/inssagram/domain/stroy/StoryScheduler.java
  src/main/java/com/be/inssagram/domain/stroy/dto/response/StoryInfoResponse.java
  src/main/java/com/be/inssagram/domain/stroy/entity/Story.java
  src/main/java/com/be/inssagram/domain/stroy/repository/StoryRepository.java
  src/main/java/com/be/inssagram/domain/stroy/service/StoryService.java
Labels: enhancement

#43 2023-11-08
  src/main/java/com/be/inssagram/domain/comment/dto/response/CommentInfoResponse.java
  src/main/java/com/be/inssagram/domain/comment/dto/response/ReplyInfoResponse.java
  src/main/java/com/be/inssagram/domain/comment/entity/Comment.java
  src/main/java/com/be/inssagram/domain/like/controller/LikeController.java
  src/main/java/com/be/inssagram/domain/like/service/LikeService.java
  src/main/java/com/be/inssagram/domain/post/dto/request/CreatePostRequest.java
  src/main/java/com/be/inssagram/domain/post/dto/request/UpdatePostRequest.java
  src/main/java/com/be/inssagram/domain/post/dto/response/PostInfoResponse.java
  src/main/java/com/be/inssagram/domain/post/entity/Post.java
  src/main/java/com/be/inssagram/domain/post/repository/PostRepository.java
  src/main/java/com/be/inssagram/domain/post/service/PostService.java
  src/main/java/com/be/inssagram/domain/post/type/PostType.java
  src/main/java/com/be/inssagram/domain/stroy/dto/response/StoryInfoResponse.java
Labels: bug, enhancement

#44 2023-11-09
  src/main/java/com/be/inssagram/InssagramApplication.java
  src/main/java/com/be/inssagram/domain/comment/dto/response/CommentInfoResponse.java
  src/main/java/com/be/inssagram/domain/comment/dto/response/ReplyInfoResponse.java
  src/main/java/com/be/inssagram/domain/comment/entity/Comment.java
  src/main/java/com/be/inssagram/domain/like/controller/LikeController.java
  src/main/java/com/be/inssagram/domain/like/service/LikeService.java
  src/main/java/com/be/inssagram/domain/post/dto/request/CreatePostRequest.java
  src/main/java/com/be/inssagram/domain/post/dto/request/UpdatePostRequest.java
  src/main/java/com/be/inssagram/domain/post/dto/response/PostInfoResponse.java
  src/main/java/com/be/inssagram/domain/post/entity/Post.java
  src/main/java/com/be/inssagram/domain/post/repository/PostRepository.java
  src/main/java/com/be/inssagram/domain/post/service/PostService.java
  src/main/java/com/be/inssagram/domain/post/type/PostType.java
  src/main/java/com/be/inssagram/domain/stroy/StoryScheduler.java
  src/main/java/com/be/inssagram/domain/stroy/dto/response/StoryInfoResponse.java
  src/main/java/com/be/inssagram/domain/stroy/entity/Story.java
  src/main/java/com/be/inssagram/domain/stroy/repository/StoryRepository.java
  src/main/java/com/be/inssagram/domain/stroy/service/StoryService.java
Labels: enhancement

#45 2023.11.09
  src/main/java/com/be/inssagram/domain/comment/service/CommentService.java
  src/main/java/com/be/inssagram/domain/elastic/documents/index/HistoryIndex.java
  src/main/java/com/be/inssagram/domain/elastic/documents/repository/HistorySearchRepository.java
  src/main/java/com/be/inssagram/domain/elastic/dto/response/SearchResult.java
  src/main/java/com/be/inssagram/domain/elastic/service/ElasticSearchService.java
  src/main/java/com/be/inssagram/domain/follow/controller/FollowController.java
  src/main/java/com/be/inssagram/domain/follow/dto/request/FollowRequest.java
  src/main/java/com/be/inssagram/domain/follow/entity/Follow.java
  src/main/java/com/be/inssagram/domain/follow/repository/FollowRepository.java
  src/main/java/com/be/inssagram/domain/follow/service/FollowService.java
  src/main/java/com/be/inssagram/domain/hashTag/service/HashTagService.java
  src/main/java/com/be/inssagram/domain/like/service/LikeService.java
  src/main/java/com/be/inssagram/domain/member/controller/MemberController.java
  src/main/java/com/be/inssagram/domain/member/service/MemberService.java
  src/main/java/com/be/inssagram/domain/notification/service/NotificationService.java
  src/main/resources/elastic/history-mapping.json
Labels: documentation, enhancement
